version: '3.9'
services:
  nginx:
    build:
      # FIXME: Use the published image here instead
      context: ../
      target: nginx-with-auth
    ports:
      - '80:80'
    networks:
      - nginx
    depends_on:
      - server
    volumes:
      - './nginx.conf:/etc/nginx/conf.d/default.conf'
      - './config.conf:/etc/nginx/config.conf'

  server:
    build:
      context: ./.
      target: server
    networks:
      - nginx
    restart: unless-stopped

networks:
  nginx: